name: Actions Workflow
on:
  pull_request:
    types: [closed, reopened, assigned, opened]
jobs:
  simple_javascript_action:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Cloning with Github checkout action
        uses: actions/checkout@v3.0.2
      - name: Listing files after checkout
        run: |
          pwd
          ls -a
      - name: Greet the Person
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Ganesh
      - name: Log the Greet time
        run: echo "${{steps.greet.outputs.time}}"
