name: Actions Workflow
on: push
jobs:
  simple_javascript_action:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Cloning files
        run: |
          git --version
          git clone git@github.com:ganeshkumarburra/github-actions-test.git
          pwd
          ls -a
      - name: Greet the Person
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Ganesh
      - name: Log the Greet time
        run: echo "${{steps.greet.outputs.time}}"
