name: Container
on: push
jobs:
  docker-container-insteps:
    runs-on: ubuntu-latest
    container:
      image: node:14
    steps:
      - name: Main container node version
        run: node --version
      - name: Container in steps with echo
        uses: docker://node:12
        with:
          entrypoint: "/bin/echo"
          args: "Hello world"
      - name: Container in steps with node version logging
        uses: docker://node:10
        with:
          entrypoint: "/usr/local/bin/node"
          args: -v
      - name: Cloning the repo
        uses: actions/checkout@v2
      - name: Runing script
        uses: docker://node:10
        with:
          entrypoint: "./script.sh"
          args: "Roopa"
  docker-container:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - "3001:3000"
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Get a users
        run: curl http://localhost:3001/api/users
