name: Container
on: push
jobs:
  docker-container:
    runs-on: ubuntu-latest
    container:
      image: node:14
    steps:
      - name: Docker version
        run: |
          node -v
          cat /etc/os-release
