name: Container
on: push
jobs:
  docker-container:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - "3001:3000"
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl --location --request POST "http://localhost:3001/api/users" --header "Content-Type: application/json" --data-raw "{"username":"Ganesh","address":"Kothavaripalle"}"'
      - name: Get a users
        run: curl http://localhost:3001/api/users
