name: Container
on: push
jobs:
  docker-container:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - "3001:3000"
      mongo:
        image: mongo
        ports:
          - "27017:27017"
        volumes:
          - ~/apps/mongo:/data/db`
    steps:
      - name: Get a users
        run: curl http://localhost:3001/api/users
