name: Evironment variables
on: workflow_dispatch
env:
  WF_ENV: Available for all jobs
permissions: write-all
jobs:
  decrypt_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypting the file
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
        run: gpg --quiet --batch --yes --decrypt --passphrase=$PASSPHRASE --output $HOME/secret.txt secret.txt.gpg
      - name: Decrypted data
        run: cat $HOME/secret.txt
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - name: Adding Random Number
        if: false
        run: |
          pwd
          ls
          git init
          git remote add origin "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull  
          ls
          echo $RANDOM >> random.txt
          ls
          git add -A
          git commit -m "Random number added"
          git remote -v
          git push
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: master

      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available in only log-env job
    steps:
      - name: Logging variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Logging Default variable
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
