name: Matrix
on: push
jobs:
  node-version:
    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Log initial node version
        run: node --version
      - name: node version 8
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Log new node version
        run: node --version
