name: Experiment-New
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3.0.2
      - name: List files
        run: ls
