name: Shell Commands
on:
  repository_dispatch:
    types: [build]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.env}}
      - name: echo a string
        run: echo "Hello world"
      - name: multi line script
        run: |
          npm --version
          node --version
      - name: python shell command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Get PowerShell Directory
        run: Get-Location
      - name: Get shell directory
        run: pwd
        shell: bash
